data<-read.delim(file="household_power_consumption.txt",sep=";",header=T)
sdata<-subset(data,as.Date(Date,format="%d/%m/%Y")>="2007-02-01" & as.Date(Date,format="%d/%m/%Y")<="2007-02-02")
sdata$DateTime <- paste(sdata$Date, sdata$Time, sep = " ")
sdata$DateTime <- strptime(sdata$DateTime, format = "%d/%m/%Y %H:%M:%S")
png(filename = "plot3.png", width = 480, height = 480, units = "px")
plot(sdata$DateTime, sdata$Sub_metering_1, type = "l", main = NULL, xlab = "", ylab = "Energy sub metering")
points(sdata$DateTime, sdata$Sub_metering_2, type = "l", col = "red")
points(sdata$DateTime, sdata$Sub_metering_3, type = "l", col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),cex = 0.9,col = c("black", "red", "blue"), lty = 1)
dev.off()