data<-read.delim(file="household_power_consumption.txt",sep=";",header=T)
sdata<-subset(data,as.Date(Date,format="%d/%m/%Y")>="2007-02-01" & as.Date(Date,format="%d/%m/%Y")<="2007-02-02")
png(filename = "plot4.png", width = 480, height = 480, units = "px")
par(mfrow = c(2, 2), cex = 0.7)
plot(sdata$DateTime, sdata$Global_active_power, type = "l", main = NULL, xlab = "", ylab = "Global Active Power")
plot(sdata$DateTime, sdata$Voltage, type = "l", main = NULL, xlab = "datetime", ylab = "Voltage")
plot(sdata$DateTime, sdata$Sub_metering_1, type = "l", main = NULL, xlab = "", ylab = "Energy sub metering")
points(sdata$DateTime, sdata$Sub_metering_2, type = "l", col = "red")
points(sdata$DateTime, sdata$Sub_metering_3, type = "l", col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),bty = "n", col = c("black", "red", "blue"), lty = 1)
plot(sdata$DateTime, sdata$Global_reactive_power, type = "l", main = NULL, xlab = "datetime", ylab = "Global_reactive_power", yaxt = "n")
axis(side = 2, at = c(0.0, 0.1, 0.2, 0.3, 0.4, 0.5), labels = c("0.0", "0.1", "0.2", "0.3", "0.4", "0.5"))
dev.off()